package model

type Entity_Cacheucarbasicinfo_Full struct {

	// AlternateContact
	AlternateContact string
	// BrandID
	BrandID string
	// BuyCarDate
	BuyCarDate string
	// CalcCarPrice
	CalcCarPrice string
	// CarCityId
	CarCityId string
	// CardCode
	CardCode string
	// CarDistrictId
	CarDistrictId string
	// CarDownTime
	CarDownTime string
	// CardRangeID
	CardRangeID string
	// CarID
	CarID string
	// CarProviceId
	CarProviceId string
	// CarPublishTime
	CarPublishTime string
	// CarSetting
	CarSetting string
	// 车辆来源1级分类（1：个人车源 2：车商通(商家)车源  3：一线通  4：其他）
	CarSource1L string
	// 车辆来源2级分类(1：个人自主上传  5：4S店  6：专业公司  9：其他商家(经纪人)  11：非注册个人用户)
	CarSource2L string
	// CarSourceStatus
	CarSourceStatus string
	// CarType
	CarType string
	// CheckedTime
	CheckedTime string
	// Color
	Color string
	// CompleteRate
	CompleteRate string
	// 联系方式
	Contact string
	// Coordinate
	Coordinate string
	// CreateTime
	CreateTime string
	// DisplayPrice
	DisplayPrice string
	// DriveLicensePic
	DriveLicensePic string
	// DrivingMileage
	DrivingMileage string
	// ExamineExpireDate
	ExamineExpireDate string
	// Exhaust
	Exhaust string
	// ExhaustValue
	ExhaustValue string
	// Fee
	Fee string
	// FirstPicTrue
	FirstPicTrue string
	// GearBoxType
	GearBoxType string
	// InnerColor
	InnerColor string
	// InsuranceExpireDate
	InsuranceExpireDate string
	// IsAuthenticated
	IsAuthenticated string
	// IsCards
	IsCards string
	// IsChangePrice
	IsChangePrice string
	// IsDealerRecommend
	IsDealerRecommend string
	// 是否包含过户
	IsIncTransfer string
	// IsLicensed
	IsLicensed string
	// IsNeglect
	IsNeglect string
	// IsTransferToOld
	IsTransferToOld string
	// IsVideoCar
	IsVideoCar string
	// LandMarkBuilding
	LandMarkBuilding string
	// LicenseCityId
	LicenseCityId string
	// LicenseCode
	LicenseCode string
	// LicenseProviceId
	LicenseProviceId string
	// 联系人
	LinkMan string
	// 联系人性别（1:男  2:女）
	LinkManSex string
	// 看车地址
	LookPlace string
	// MainBrandID
	MainBrandID string
	// MaintainRecord
	MaintainRecord string
	// picturecount
	picturecount string
	// ProducerID
	ProducerID string
	// RegUserId
	RegUserId string
	// Source
	Source string
	// StateDescription
	StateDescription string
	// StatusModifyTime
	StatusModifyTime string
	// SystemId
	SystemId string
	// UBUserId
	UBUserId string
	// UcarID
	UcarID string
	// UcarSerialNumber
	UcarSerialNumber string
	// UcarStatus
	UcarStatus string
	// UserID
	UserID string
	// UserType
	UserType string
	// VinCode
	VinCode string
	// 微信二维码
	WebchatUrl string
	// 微信号
	WechatCode string
	// 此车源图片路径
	ImgUrls string
	// 主品牌名称(为空表示主品牌不存在)
	MBrand_Name string
	// 主品牌构造 Url 的拼音
	MBrand_UrlSpell string
	// 车系显示名称(为空表示车系不存在)
	Serial_ShowName string
	// 车系拼音
	Serial_AllSpell string
	// 车辆级别名称
	CarLevelName string
	// 车辆级别类型
	CarLevelType string
	// 变速箱名称
	GearBoxName string
	// 车型名称(为空表示车型不存在)
	Basic_Name string
	// 车型年款
	CarYear string
	// 车型信息中的排量
	Basic_Exhaust string
	// 发动机增压方式(涡轮增压，涡轮机械双增压，双涡轮增压，机械增压，待查，无)
	AddPressType string
	// 平均油耗
	Consumption string
	// 新车厂商指导价(单位：万元)
	NewCarPrice string
	// 手机扫描二维码指向的链接
	QrCodeUrl string
	// 车源亮点，返回的每个字符串中可能含有占位符 string，对应当前页面中的二级域名名称,如 www 或 beijing
	// <para>占位符在显示时需要过滤掉</para>
	CarHighLights string
	// 经销商服务
	DealerService string
	// 是否代办过户(是否包含过户费使用 IsIncTransfer 属性)
	IsTransferAgent string
	// 小编推荐(专家推荐)
	Recommend string
	// 广告语
	Slogan string
	// 是否疑似商家
	IsDealerCar string
	// 联系电话
	Tell  string
	// 联系电话2
	Tell2 string
	// 联系人2
	LinkMan2 string
	// 微信号2
	WechatCode2 string
	// 是否保障车:0非保障车；1保障车；-1所有
	IsWarranty string
	// 保障服务类型:1原厂质保;2延长质保;4免费过户
	WarrantyTypes string
	// 是否维保：1维保；0非维保；-1所有
	IsShowMr string
	// 原生电话1
	ProtogTel string
	// 原生电话2
	ProtogTel1 string
	// 淘车认证标志
	IsDealerAuthorized string
}
